### ISSUE TITLE
Revisión preliminar de resultados de exclusión fija

### ISSUE THREAD

**Issue by m4wnn** [DIE-BANGUAT/EMI-mkdocs#2]
Lectura preliminar de los resultados. Falta añadir el análisis de sensibilidad por tipo de muestreo, análisis de trayectorias y las nueva descomposición del MSE.

**Comment by r2cp** [comment]
- Revisado con e7f23e04fb4583c9b036297595ade7090f187158
- Revisión de gráficas en c57b16731e0e0558f76fa19d64ada98bb4b936a2 y 4ad7e4d72c40d4de431c3d05c71f91e39c88b0f7
- Reubicación de gráficas por tipos de medidas de inflación en a186fd8a2e072ea1007b1576727b3dd4c0893de8
